name : Continuous Integration 

on:
    push:
        branches: 
            - main
    pull_request:
        branches: 
            - main 

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x,14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: set Up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
            
      - name: install dependencies
        run: npm install
        working-directory: 1-4project

      - name: run tests
        run: npm run test -- --run
        working-directory: 1-4project